// ===========================================================================
// trivia-content.js  —  YOUR QUESTION BANK (edit freely)
// 7 categories x 5 difficulty levels x 10 questions.
// Each question: { q: "text", a: ["opt0","opt1","opt2","opt3"], c: correctIndex }
// c is the 0-based index of the correct option.
// The host draws questions MIXED across categories at the chosen level, with no
// repeats until the level's pool is exhausted. Keep facts evergreen (avoid
// "current"/"latest" facts that go stale).
// English v1; structured so a second language can be added later.
// ===========================================================================

export const CATEGORIES = [
  "General Knowledge", "Fun & Pop Culture", "Science & Nature",
  "Geography", "History", "Words & Language", "Movies & TV",
];

export const DIFFICULTY_LABELS = {
  1: "Level 1 · Easiest", 2: "Level 2 · Easy", 3: "Level 3 · Medium",
  4: "Level 4 · Hard", 5: "Level 5 · Hardest",
};
export const DEFAULT_DIFFICULTY = 2;

export const TRIVIA = {
  "General Knowledge": {
    1: [
      { q: "How many days are in a week?", a: ["5", "6", "7", "8"], c: 2 },
      { q: "What color do you get by mixing blue and yellow?", a: ["Green", "Purple", "Orange", "Brown"], c: 0 },
      { q: "How many legs does a spider have?", a: ["6", "8", "10", "12"], c: 1 },
      { q: "What is the opposite of 'hot'?", a: ["Warm", "Cold", "Wet", "Dry"], c: 1 },
      { q: "Which animal is known as 'man's best friend'?", a: ["Cat", "Horse", "Dog", "Rabbit"], c: 2 },
      { q: "How many sides does a triangle have?", a: ["2", "3", "4", "5"], c: 1 },
      { q: "What do bees make?", a: ["Milk", "Honey", "Silk", "Wax only"], c: 1 },
      { q: "Which meal is eaten in the morning?", a: ["Dinner", "Lunch", "Breakfast", "Supper"], c: 2 },
      { q: "What shape is a stop sign?", a: ["Circle", "Square", "Triangle", "Octagon"], c: 3 },
      { q: "How many colors are in a rainbow?", a: ["5", "6", "7", "9"], c: 2 },
    ],
    2: [
      { q: "How many continents are there on Earth?", a: ["5", "6", "7", "8"], c: 2 },
      { q: "What is the largest planet in our solar system?", a: ["Earth", "Saturn", "Jupiter", "Neptune"], c: 2 },
      { q: "How many minutes are in an hour?", a: ["30", "60", "90", "100"], c: 1 },
      { q: "What is frozen water called?", a: ["Steam", "Ice", "Snowflake only", "Vapor"], c: 1 },
      { q: "Which is the tallest animal in the world?", a: ["Elephant", "Giraffe", "Horse", "Camel"], c: 1 },
      { q: "How many players are on a soccer team on the field?", a: ["9", "10", "11", "12"], c: 2 },
      { q: "What gas do humans need to breathe to live?", a: ["Carbon dioxide", "Oxygen", "Helium", "Nitrogen"], c: 1 },
      { q: "What is the currency used in the United States?", a: ["Euro", "Pound", "Dollar", "Yen"], c: 2 },
      { q: "Which planet is known as the Red Planet?", a: ["Venus", "Mars", "Mercury", "Jupiter"], c: 1 },
      { q: "How many strings does a standard guitar have?", a: ["4", "5", "6", "7"], c: 2 },
    ],
    3: [
      { q: "How many bones are in the adult human body?", a: ["186", "206", "226", "246"], c: 1 },
      { q: "What is the hardest natural substance on Earth?", a: ["Gold", "Iron", "Diamond", "Quartz"], c: 2 },
      { q: "How many degrees are in a right angle?", a: ["45", "90", "180", "360"], c: 1 },
      { q: "What is the chemical symbol for gold?", a: ["Go", "Gd", "Au", "Ag"], c: 2 },
      { q: "Which ocean is the largest?", a: ["Atlantic", "Indian", "Arctic", "Pacific"], c: 3 },
      { q: "How many players are on a basketball team on the court?", a: ["4", "5", "6", "7"], c: 1 },
      { q: "What is the boiling point of water in Celsius at sea level?", a: ["90", "100", "110", "120"], c: 1 },
      { q: "Which is the smallest prime number?", a: ["0", "1", "2", "3"], c: 2 },
      { q: "What instrument has 88 keys?", a: ["Organ", "Piano", "Harpsichord", "Accordion"], c: 1 },
      { q: "How many zeros are in one million?", a: ["4", "5", "6", "7"], c: 2 },
    ],
    4: [
      { q: "What is the most abundant gas in Earth's atmosphere?", a: ["Oxygen", "Carbon dioxide", "Nitrogen", "Argon"], c: 2 },
      { q: "How many hearts does an octopus have?", a: ["1", "2", "3", "4"], c: 2 },
      { q: "What is the square root of 144?", a: ["11", "12", "13", "14"], c: 1 },
      { q: "Which vitamin is produced when skin is exposed to sunlight?", a: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], c: 3 },
      { q: "What is the study of fungi called?", a: ["Botany", "Mycology", "Zoology", "Ecology"], c: 1 },
      { q: "How many time zones does Russia span?", a: ["7", "9", "11", "13"], c: 2 },
      { q: "What is the smallest bone in the human body?", a: ["Stapes", "Femur", "Radius", "Patella"], c: 0 },
      { q: "Which metal is liquid at room temperature?", a: ["Lead", "Mercury", "Aluminum", "Zinc"], c: 1 },
      { q: "What number is a 'baker's dozen'?", a: ["10", "12", "13", "14"], c: 2 },
      { q: "What is the fear of spiders called?", a: ["Acrophobia", "Arachnophobia", "Claustrophobia", "Agoraphobia"], c: 1 },
    ],
    5: [
      { q: "What is the only number that is neither prime nor composite?", a: ["0", "1", "2", "-1"], c: 1 },
      { q: "How many chambers does a human heart have?", a: ["2", "3", "4", "5"], c: 2 },
      { q: "What is the SI unit of electric current?", a: ["Volt", "Watt", "Ampere", "Ohm"], c: 2 },
      { q: "The Fibonacci sequence begins 0, 1, 1, 2, 3, 5, 8 — what comes next?", a: ["11", "13", "15", "21"], c: 1 },
      { q: "What is the largest internal organ in the human body?", a: ["Brain", "Liver", "Lungs", "Kidney"], c: 1 },
      { q: "In music, how many semitones are in an octave?", a: ["7", "8", "12", "13"], c: 2 },
      { q: "What is the term for an angle greater than 180 degrees?", a: ["Obtuse", "Reflex", "Acute", "Straight"], c: 1 },
      { q: "Which element has the atomic number 1?", a: ["Helium", "Oxygen", "Hydrogen", "Carbon"], c: 2 },
      { q: "What is the collective noun for a group of crows?", a: ["A pack", "A murder", "A flock", "A herd"], c: 1 },
      { q: "How many faces does a dodecahedron have?", a: ["10", "12", "16", "20"], c: 1 },
    ],
  },
  "Fun & Pop Culture": {
    1: [
      { q: "What is the name of Mickey Mouse's pet dog?", a: ["Goofy", "Pluto", "Rex", "Spot"], c: 1 },
      { q: "In 'Toy Story', what kind of toy is Woody?", a: ["Astronaut", "Cowboy", "Dinosaur", "Soldier"], c: 1 },
      { q: "What color is the character SpongeBob?", a: ["Blue", "Green", "Yellow", "Pink"], c: 2 },
      { q: "Which superhero is known as the 'Man of Steel'?", a: ["Batman", "Superman", "Spider-Man", "Thor"], c: 1 },
      { q: "What fruit features in the Apple company logo?", a: ["Orange", "Apple", "Cherry", "Pear"], c: 1 },
      { q: "Which bear loves 'hunny' in a red shirt?", a: ["Paddington", "Yogi", "Winnie the Pooh", "Baloo"], c: 2 },
      { q: "What is Batman's home city?", a: ["Metropolis", "Gotham City", "Central City", "Star City"], c: 1 },
      { q: "In emoji, what does a red heart usually mean?", a: ["Anger", "Love", "Money", "Sleep"], c: 1 },
      { q: "Which video game character is a plumber in red?", a: ["Sonic", "Luigi", "Mario", "Link"], c: 2 },
      { q: "What kind of animal is 'Nemo' in the Pixar film?", a: ["Dolphin", "Clownfish", "Shark", "Turtle"], c: 1 },
    ],
    2: [
      { q: "Which social media app is known for short videos and a musical-note logo?", a: ["Twitter", "TikTok", "LinkedIn", "Reddit"], c: 1 },
      { q: "What is the name of the wizard school in 'Harry Potter'?", a: ["Hogwarts", "Narnia", "Camelot", "Xavier's"], c: 0 },
      { q: "Which company makes the PlayStation console?", a: ["Microsoft", "Nintendo", "Sony", "Sega"], c: 2 },
      { q: "In 'Frozen', who is Elsa's younger sister?", a: ["Anna", "Belle", "Ariel", "Merida"], c: 0 },
      { q: "What is the highest card in a standard deck (ace high)?", a: ["King", "Queen", "Jack", "Ace"], c: 3 },
      { q: "Which fictional detective lives at 221B Baker Street?", a: ["Poirot", "Sherlock Holmes", "Columbo", "Marple"], c: 1 },
      { q: "What green ogre stars in a DreamWorks film series?", a: ["Hulk", "Shrek", "Gru", "Fiona"], c: 1 },
      { q: "Which streaming service is known for a red 'N' logo?", a: ["Hulu", "Netflix", "Disney+", "Prime"], c: 1 },
      { q: "In chess, which piece can only move diagonally?", a: ["Rook", "Knight", "Bishop", "Pawn"], c: 2 },
      { q: "What is the name of the coffee chain with a green mermaid logo?", a: ["Dunkin'", "Starbucks", "Peet's", "Costa"], c: 1 },
    ],
    3: [
      { q: "Which band released the album 'Abbey Road'?", a: ["The Rolling Stones", "The Beatles", "Queen", "Led Zeppelin"], c: 1 },
      { q: "In Monopoly, how much money does each player start with (standard US rules)?", a: ["$1,000", "$1,500", "$2,000", "$500"], c: 1 },
      { q: "What is the name of the toy company that makes interlocking plastic bricks?", a: ["Playmobil", "LEGO", "Mattel", "Hasbro"], c: 1 },
      { q: "Which artist painted the 'Campbell's Soup Cans'?", a: ["Picasso", "Warhol", "Dali", "Pollock"], c: 1 },
      { q: "What does the acronym 'LOL' stand for?", a: ["Lots of love", "Laugh out loud", "Live on lens", "Love our life"], c: 1 },
      { q: "In 'The Simpsons', what is the family's home town?", a: ["Springfield", "Quahog", "Shelbyville", "Ogdenville"], c: 0 },
      { q: "Which card game involves shouting 'Uno' when you have one card left?", a: ["Rummy", "Uno", "Spades", "Hearts"], c: 1 },
      { q: "What instrument did Jimi Hendrix famously play?", a: ["Drums", "Bass", "Electric guitar", "Piano"], c: 2 },
      { q: "Which classic board game uses the phrase 'You sank my battleship'?", a: ["Risk", "Battleship", "Clue", "Sorry!"], c: 1 },
      { q: "What is the name of Sherlock Holmes's doctor companion?", a: ["Dr. Watson", "Dr. House", "Dr. Jekyll", "Dr. No"], c: 0 },
    ],
    4: [
      { q: "Which composer wrote 'The Four Seasons'?", a: ["Mozart", "Beethoven", "Vivaldi", "Bach"], c: 2 },
      { q: "In the game of poker, which hand ranks highest?", a: ["Full house", "Straight", "Royal flush", "Four of a kind"], c: 2 },
      { q: "Who is the author of the 'A Song of Ice and Fire' novels?", a: ["J.R.R. Tolkien", "George R.R. Martin", "J.K. Rowling", "C.S. Lewis"], c: 1 },
      { q: "Which Italian city is the setting for Shakespeare's 'Romeo and Juliet'?", a: ["Venice", "Rome", "Verona", "Milan"], c: 2 },
      { q: "What is the best-selling video game of all time (single title)?", a: ["Tetris", "Minecraft", "Wii Sports", "Pac-Man"], c: 1 },
      { q: "Which artist is known for the pop-art 'Marilyn Diptych'?", a: ["Roy Lichtenstein", "Andy Warhol", "Keith Haring", "Jasper Johns"], c: 1 },
      { q: "In Greek myth used in pop culture, who opened a box releasing evils?", a: ["Medusa", "Pandora", "Athena", "Helen"], c: 1 },
      { q: "What was the first feature-length animated film by Disney?", a: ["Pinocchio", "Snow White and the Seven Dwarfs", "Fantasia", "Bambi"], c: 1 },
      { q: "Which rock band's logo is a tongue and lips?", a: ["The Who", "The Rolling Stones", "AC/DC", "Kiss"], c: 1 },
      { q: "What is the name of the fictional metal in the Marvel universe from Wakanda?", a: ["Adamantium", "Vibranium", "Mithril", "Kryptonite"], c: 1 },
    ],
    5: [
      { q: "Which author wrote under the pen name 'Robert Galbraith'?", a: ["Stephen King", "J.K. Rowling", "Agatha Christie", "Dan Brown"], c: 1 },
      { q: "In music theory, the notes of a C major chord are C, E, and which third?", a: ["F", "G", "A", "B"], c: 1 },
      { q: "Which painting by Edvard Munch depicts a figure holding its face?", a: ["Guernica", "The Scream", "The Kiss", "Starry Night"], c: 1 },
      { q: "What is the oldest continuously published magazine still running (US)?", a: ["Time", "Scientific American", "National Geographic", "The New Yorker"], c: 1 },
      { q: "Which chess world champion was famously beaten by IBM's Deep Blue in 1997?", a: ["Bobby Fischer", "Garry Kasparov", "Magnus Carlsen", "Anatoly Karpov"], c: 1 },
      { q: "Who composed the opera 'The Magic Flute'?", a: ["Verdi", "Wagner", "Mozart", "Puccini"], c: 2 },
      { q: "In the tarot deck, how many cards are in the Major Arcana?", a: ["21", "22", "52", "78"], c: 1 },
      { q: "Which novel opens with the line 'Call me Ishmael'?", a: ["Moby-Dick", "The Odyssey", "Great Expectations", "Robinson Crusoe"], c: 0 },
      { q: "What is the name of the auction house founded in London in 1744?", a: ["Christie's", "Sotheby's", "Bonhams", "Phillips"], c: 1 },
      { q: "Which Beatles member was the first to release a solo #1 single?", a: ["John Lennon", "Paul McCartney", "George Harrison", "Ringo Starr"], c: 2 },
    ],
  },
  "Science & Nature": {
    1: [
      { q: "What do plants need from the sun to make food?", a: ["Cold", "Light", "Sound", "Wind"], c: 1 },
      { q: "Which animal says 'moo'?", a: ["Sheep", "Cow", "Pig", "Duck"], c: 1 },
      { q: "What is baby frog called?", a: ["Cub", "Tadpole", "Kit", "Calf"], c: 1 },
      { q: "How many legs does an insect have?", a: ["4", "6", "8", "10"], c: 1 },
      { q: "What is the closest star to Earth?", a: ["The Moon", "The Sun", "Polaris", "Mars"], c: 1 },
      { q: "Which season comes after winter?", a: ["Summer", "Autumn", "Spring", "Fall"], c: 2 },
      { q: "What do we call water falling from clouds?", a: ["Rain", "Fog", "Dew", "Frost"], c: 0 },
      { q: "Which body part pumps blood?", a: ["Lungs", "Brain", "Heart", "Liver"], c: 2 },
      { q: "What color are most leaves in summer?", a: ["Red", "Green", "Blue", "Purple"], c: 1 },
      { q: "Which animal is the largest on land?", a: ["Giraffe", "Elephant", "Rhino", "Hippo"], c: 1 },
    ],
    2: [
      { q: "What force pulls objects toward the Earth?", a: ["Magnetism", "Gravity", "Friction", "Tension"], c: 1 },
      { q: "How many planets are in our solar system?", a: ["7", "8", "9", "10"], c: 1 },
      { q: "What is H2O commonly known as?", a: ["Salt", "Water", "Oxygen", "Hydrogen"], c: 1 },
      { q: "Which part of a plant absorbs water from the soil?", a: ["Leaves", "Flower", "Roots", "Stem"], c: 2 },
      { q: "What do you call animals that eat only plants?", a: ["Carnivores", "Herbivores", "Omnivores", "Insectivores"], c: 1 },
      { q: "What is the center of an atom called?", a: ["Electron", "Nucleus", "Proton shell", "Orbit"], c: 1 },
      { q: "Which gas do plants absorb from the air for photosynthesis?", a: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], c: 2 },
      { q: "How many teeth does a typical adult human have?", a: ["28", "30", "32", "36"], c: 2 },
      { q: "What is the fastest land animal?", a: ["Lion", "Cheetah", "Horse", "Gazelle"], c: 1 },
      { q: "What state of matter is steam?", a: ["Solid", "Liquid", "Gas", "Plasma"], c: 2 },
    ],
    3: [
      { q: "What is the powerhouse of the cell?", a: ["Nucleus", "Ribosome", "Mitochondria", "Vacuole"], c: 2 },
      { q: "Which planet is closest to the Sun?", a: ["Venus", "Mercury", "Earth", "Mars"], c: 1 },
      { q: "What type of blood cells fight infection?", a: ["Red", "White", "Platelets", "Plasma"], c: 1 },
      { q: "What is the process by which liquid turns to gas?", a: ["Condensation", "Evaporation", "Freezing", "Melting"], c: 1 },
      { q: "How many legs does a lobster have (including claws)?", a: ["6", "8", "10", "12"], c: 2 },
      { q: "What is the chemical symbol for sodium?", a: ["So", "Sd", "Na", "S"], c: 2 },
      { q: "Which is the largest organ of the human body?", a: ["Liver", "Skin", "Brain", "Lungs"], c: 1 },
      { q: "What do we call an animal active at night?", a: ["Diurnal", "Nocturnal", "Crepuscular", "Hibernating"], c: 1 },
      { q: "What planet is famous for its prominent rings?", a: ["Jupiter", "Saturn", "Uranus", "Neptune"], c: 1 },
      { q: "What gas makes up about 21% of Earth's atmosphere?", a: ["Nitrogen", "Oxygen", "Carbon dioxide", "Argon"], c: 1 },
    ],
    4: [
      { q: "What is the speed of light approximately (in a vacuum)?", a: ["300,000 km/s", "150,000 km/s", "1,000 km/s", "30,000 km/s"], c: 0 },
      { q: "Which scientist proposed the theory of general relativity?", a: ["Newton", "Einstein", "Bohr", "Galileo"], c: 1 },
      { q: "What is the pH of a neutral solution?", a: ["0", "7", "10", "14"], c: 1 },
      { q: "What type of animal is a Komodo dragon?", a: ["Snake", "Lizard", "Crocodile", "Amphibian"], c: 1 },
      { q: "Which planet has the most moons in our solar system (giant planets)?", a: ["Earth", "Mars", "Saturn", "Mercury"], c: 2 },
      { q: "What is the hardest known natural material?", a: ["Steel", "Diamond", "Titanium", "Granite"], c: 1 },
      { q: "What is the process of cell division that produces gametes?", a: ["Mitosis", "Meiosis", "Osmosis", "Fission"], c: 1 },
      { q: "Which element has the chemical symbol 'Fe'?", a: ["Fluorine", "Iron", "Francium", "Lead"], c: 1 },
      { q: "What part of the brain controls balance and coordination?", a: ["Cerebrum", "Cerebellum", "Brainstem", "Hypothalamus"], c: 1 },
      { q: "How long does light from the Sun take to reach Earth (approx.)?", a: ["8 seconds", "8 minutes", "8 hours", "8 days"], c: 1 },
    ],
    5: [
      { q: "What is the most abundant element in the universe?", a: ["Oxygen", "Carbon", "Hydrogen", "Helium"], c: 2 },
      { q: "Who is credited with formulating the laws of planetary motion?", a: ["Copernicus", "Kepler", "Brahe", "Halley"], c: 1 },
      { q: "What is the term for the pressure exerted by a fluid at equilibrium due to gravity?", a: ["Osmotic pressure", "Hydrostatic pressure", "Partial pressure", "Vapor pressure"], c: 1 },
      { q: "Which subatomic particle has no electric charge?", a: ["Proton", "Electron", "Neutron", "Positron"], c: 2 },
      { q: "What is the study of the interactions between living organisms and their environment?", a: ["Ecology", "Etymology", "Entomology", "Epidemiology"], c: 0 },
      { q: "Absolute zero is approximately what temperature in Celsius?", a: ["0°C", "-100°C", "-273°C", "-459°C"], c: 2 },
      { q: "Which vitamin deficiency causes scurvy?", a: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], c: 1 },
      { q: "What is the name of the galaxy that contains our solar system?", a: ["Andromeda", "The Milky Way", "Triangulum", "Whirlpool"], c: 1 },
      { q: "In DNA, adenine always pairs with which base?", a: ["Guanine", "Cytosine", "Thymine", "Uracil"], c: 2 },
      { q: "What is the SI unit of force?", a: ["Joule", "Newton", "Pascal", "Watt"], c: 1 },
    ],
  },
  "Geography": {
    1: [
      { q: "Which is the largest ocean on Earth?", a: ["Atlantic", "Pacific", "Indian", "Arctic"], c: 1 },
      { q: "What is the capital of the United States?", a: ["New York", "Los Angeles", "Washington, D.C.", "Chicago"], c: 2 },
      { q: "On which continent is Egypt located?", a: ["Asia", "Europe", "Africa", "Australia"], c: 2 },
      { q: "Which country is shaped like a boot?", a: ["Spain", "Italy", "Greece", "France"], c: 1 },
      { q: "What is the tallest mountain on Earth (above sea level)?", a: ["K2", "Mount Everest", "Kilimanjaro", "Denali"], c: 1 },
      { q: "Which is the largest continent by area?", a: ["Africa", "Asia", "Europe", "North America"], c: 1 },
      { q: "What large sandy region covers much of North Africa?", a: ["Gobi", "Sahara", "Mojave", "Kalahari"], c: 1 },
      { q: "Which country has the Eiffel Tower?", a: ["Italy", "Germany", "France", "Spain"], c: 2 },
      { q: "What is the capital of Japan?", a: ["Beijing", "Seoul", "Tokyo", "Bangkok"], c: 2 },
      { q: "Which ocean is on the east coast of the United States?", a: ["Pacific", "Atlantic", "Indian", "Arctic"], c: 1 },
    ],
    2: [
      { q: "What is the longest river in the world (commonly cited)?", a: ["Amazon", "Nile", "Yangtze", "Mississippi"], c: 1 },
      { q: "Which country is both in Europe and Asia and has Istanbul?", a: ["Greece", "Turkey", "Russia", "Egypt"], c: 1 },
      { q: "What is the capital of Canada?", a: ["Toronto", "Vancouver", "Ottawa", "Montreal"], c: 2 },
      { q: "Which desert is the largest cold desert?", a: ["Sahara", "Antarctic", "Gobi", "Arabian"], c: 1 },
      { q: "What is the smallest country in the world?", a: ["Monaco", "Vatican City", "San Marino", "Malta"], c: 1 },
      { q: "The Great Barrier Reef is off the coast of which country?", a: ["Brazil", "Australia", "Mexico", "Indonesia"], c: 1 },
      { q: "Which US state is the largest by area?", a: ["Texas", "California", "Alaska", "Montana"], c: 2 },
      { q: "What is the capital of Australia?", a: ["Sydney", "Melbourne", "Canberra", "Perth"], c: 2 },
      { q: "Mount Fuji is located in which country?", a: ["China", "South Korea", "Japan", "Nepal"], c: 2 },
      { q: "Which river runs through London?", a: ["Seine", "Thames", "Danube", "Rhine"], c: 1 },
    ],
    3: [
      { q: "What is the capital of Brazil?", a: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], c: 2 },
      { q: "Which mountain range separates Europe and Asia?", a: ["Andes", "Alps", "Ural", "Rockies"], c: 2 },
      { q: "What is the largest country in the world by area?", a: ["Canada", "China", "USA", "Russia"], c: 3 },
      { q: "Which sea lies between Europe and Africa?", a: ["Red Sea", "Black Sea", "Mediterranean Sea", "Caspian Sea"], c: 2 },
      { q: "The Amazon rainforest is mostly in which country?", a: ["Peru", "Colombia", "Brazil", "Venezuela"], c: 2 },
      { q: "What is the capital of Egypt?", a: ["Cairo", "Alexandria", "Giza", "Luxor"], c: 0 },
      { q: "Which country has the most people (historically most populous)?", a: ["India", "China", "USA", "Indonesia"], c: 1 },
      { q: "What line divides the Earth into Northern and Southern hemispheres?", a: ["Prime Meridian", "Tropic of Cancer", "Equator", "Arctic Circle"], c: 2 },
      { q: "Which African country was never colonized (commonly cited)?", a: ["Kenya", "Ethiopia", "Ghana", "Nigeria"], c: 1 },
      { q: "The Strait of Gibraltar connects the Mediterranean to which ocean?", a: ["Indian", "Pacific", "Atlantic", "Arctic"], c: 2 },
    ],
    4: [
      { q: "What is the capital of Kazakhstan?", a: ["Almaty", "Astana", "Tashkent", "Bishkek"], c: 1 },
      { q: "Which country has the most natural lakes?", a: ["USA", "Russia", "Canada", "Finland"], c: 2 },
      { q: "The Atacama Desert, one of the driest places, is in which country?", a: ["Peru", "Chile", "Argentina", "Bolivia"], c: 1 },
      { q: "Which two countries share the longest international border?", a: ["USA and Mexico", "Russia and China", "USA and Canada", "Argentina and Chile"], c: 2 },
      { q: "What is the capital of New Zealand?", a: ["Auckland", "Wellington", "Christchurch", "Hamilton"], c: 1 },
      { q: "Lake Baikal, the deepest lake, is located in which country?", a: ["Mongolia", "China", "Russia", "Kazakhstan"], c: 2 },
      { q: "Which country is home to the ancient city of Petra?", a: ["Egypt", "Jordan", "Iraq", "Lebanon"], c: 1 },
      { q: "What is the highest waterfall in the world?", a: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"], c: 2 },
      { q: "Which peninsula is Spain and Portugal located on?", a: ["Balkan", "Iberian", "Italian", "Scandinavian"], c: 1 },
      { q: "The Panama Canal connects the Atlantic to which ocean?", a: ["Indian", "Pacific", "Arctic", "Southern"], c: 1 },
    ],
    5: [
      { q: "What is the capital of Mongolia?", a: ["Ulaanbaatar", "Astana", "Bishkek", "Tashkent"], c: 0 },
      { q: "Which country has the most time zones (including territories)?", a: ["Russia", "USA", "France", "China"], c: 2 },
      { q: "What is the least populous capital city in the world (commonly cited)?", a: ["Reykjavik", "Ngerulmud", "Valletta", "Vaduz"], c: 1 },
      { q: "The Danube River flows through how many countries?", a: ["4", "7", "10", "14"], c: 2 },
      { q: "Which country is the only one to border both the Atlantic and Indian Oceans and lies at Africa's southern tip?", a: ["Namibia", "Mozambique", "South Africa", "Angola"], c: 2 },
      { q: "What is the capital of Canada's province of Ontario?", a: ["Ottawa", "Toronto", "Hamilton", "London"], c: 1 },
      { q: "Which landlocked country is entirely surrounded by South Africa (mostly)?", a: ["Botswana", "Lesotho", "Eswatini", "Zimbabwe"], c: 1 },
      { q: "What is the world's largest island (not a continent)?", a: ["Madagascar", "Borneo", "Greenland", "New Guinea"], c: 2 },
      { q: "The Ural and Caspian regions mark the boundary between which two continents?", a: ["Europe and Africa", "Europe and Asia", "Asia and Africa", "Asia and Oceania"], c: 1 },
      { q: "Which is the only U.S. state that borders just one other state?", a: ["Rhode Island", "Maine", "Florida", "Hawaii"], c: 1 },
    ],
  },
  "History": {
    1: [
      { q: "Who was the first President of the United States?", a: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], c: 1 },
      { q: "What large structure in China is visible for thousands of miles?", a: ["Great Wall", "Forbidden City", "Terracotta Army", "Grand Canal"], c: 0 },
      { q: "Which ship famously sank in 1912 after hitting an iceberg?", a: ["Lusitania", "Titanic", "Mayflower", "Bismarck"], c: 1 },
      { q: "Ancient pyramids are most associated with which country?", a: ["Greece", "Egypt", "Italy", "India"], c: 1 },
      { q: "Who is said to have discovered the Americas in 1492?", a: ["Magellan", "Columbus", "Cook", "Vespucci"], c: 1 },
      { q: "What were knights known for wearing in battle?", a: ["Togas", "Armor", "Robes", "Suits"], c: 1 },
      { q: "Which ancient people built the Colosseum?", a: ["Greeks", "Romans", "Egyptians", "Persians"], c: 1 },
      { q: "Dinosaurs lived long before humans — true or false?", a: ["True", "False", "Same time", "Only fish did"], c: 0 },
      { q: "What was used before cars for common transport?", a: ["Planes", "Horses", "Rockets", "Trains only"], c: 1 },
      { q: "Which US president is on the one-dollar bill?", a: ["Lincoln", "Washington", "Jefferson", "Franklin"], c: 1 },
    ],
    2: [
      { q: "In which year did World War II end?", a: ["1918", "1939", "1945", "1950"], c: 2 },
      { q: "Who was the British Prime Minister during most of World War II?", a: ["Neville Chamberlain", "Winston Churchill", "Clement Attlee", "Tony Blair"], c: 1 },
      { q: "The Declaration of Independence was signed in which year?", a: ["1492", "1776", "1812", "1865"], c: 1 },
      { q: "Which ancient wonder still stands in Egypt?", a: ["Hanging Gardens", "Great Pyramid of Giza", "Colossus of Rhodes", "Lighthouse of Alexandria"], c: 1 },
      { q: "Who led India's nonviolent independence movement?", a: ["Nehru", "Gandhi", "Bose", "Patel"], c: 1 },
      { q: "The Berlin Wall fell in which decade?", a: ["1960s", "1970s", "1980s", "2000s"], c: 2 },
      { q: "Which empire was ruled by Julius Caesar's successors?", a: ["Greek", "Roman", "Ottoman", "British"], c: 1 },
      { q: "Who was the first man to walk on the Moon?", a: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "Michael Collins"], c: 1 },
      { q: "The American Civil War was primarily fought in which century?", a: ["17th", "18th", "19th", "20th"], c: 2 },
      { q: "Which queen has the longest reign in British history?", a: ["Victoria", "Elizabeth I", "Elizabeth II", "Anne"], c: 2 },
    ],
    3: [
      { q: "Who wrote the Communist Manifesto with Friedrich Engels?", a: ["Lenin", "Karl Marx", "Stalin", "Trotsky"], c: 1 },
      { q: "The Renaissance began in which country?", a: ["France", "England", "Italy", "Spain"], c: 2 },
      { q: "Which war was fought between the North and South in the US?", a: ["Revolutionary War", "Civil War", "War of 1812", "Spanish-American War"], c: 1 },
      { q: "Who was the Egyptian queen known for relationships with Caesar and Mark Antony?", a: ["Nefertiti", "Cleopatra", "Hatshepsut", "Isis"], c: 1 },
      { q: "In what year did the Titanic sink?", a: ["1905", "1912", "1918", "1923"], c: 1 },
      { q: "The Magna Carta was signed in which country?", a: ["France", "England", "Germany", "Italy"], c: 1 },
      { q: "Who painted the ceiling of the Sistine Chapel?", a: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], c: 1 },
      { q: "Which empire built Machu Picchu?", a: ["Aztec", "Maya", "Inca", "Olmec"], c: 2 },
      { q: "The first successful powered airplane flight was by which brothers?", a: ["The Montgolfier brothers", "The Wright brothers", "The Lumière brothers", "The Grimm brothers"], c: 1 },
      { q: "Who was assassinated in Dallas in 1963?", a: ["Abraham Lincoln", "John F. Kennedy", "Martin Luther King Jr.", "Robert Kennedy"], c: 1 },
    ],
    4: [
      { q: "The Hundred Years' War was fought mainly between England and which country?", a: ["Spain", "France", "Germany", "Italy"], c: 1 },
      { q: "Who was the first Emperor of Rome?", a: ["Julius Caesar", "Augustus", "Nero", "Caligula"], c: 1 },
      { q: "In which year did the French Revolution begin?", a: ["1776", "1789", "1804", "1815"], c: 1 },
      { q: "Which treaty ended World War I?", a: ["Treaty of Paris", "Treaty of Versailles", "Treaty of Ghent", "Treaty of Tordesillas"], c: 1 },
      { q: "Who was the leader of the Soviet Union during the Cuban Missile Crisis?", a: ["Stalin", "Khrushchev", "Brezhnev", "Gorbachev"], c: 1 },
      { q: "The Black Death peaked in Europe during which century?", a: ["12th", "14th", "16th", "18th"], c: 1 },
      { q: "Which explorer's expedition first circumnavigated the globe?", a: ["Columbus", "Magellan", "Drake", "Vasco da Gama"], c: 1 },
      { q: "Who was the longest-serving US president (terms)?", a: ["Lincoln", "Franklin D. Roosevelt", "Reagan", "Washington"], c: 1 },
      { q: "The ancient Library of Alexandria was located in which country?", a: ["Greece", "Egypt", "Turkey", "Italy"], c: 1 },
      { q: "Which dynasty built much of the Great Wall of China as seen today?", a: ["Han", "Tang", "Ming", "Qing"], c: 2 },
    ],
    5: [
      { q: "In what year did the Roman Empire's western half traditionally fall?", a: ["313 AD", "410 AD", "476 AD", "800 AD"], c: 2 },
      { q: "Who was the first female Prime Minister of the United Kingdom?", a: ["Theresa May", "Margaret Thatcher", "Angela Merkel", "Indira Gandhi"], c: 1 },
      { q: "The Peloponnesian War was fought between Athens and which city-state?", a: ["Thebes", "Corinth", "Sparta", "Troy"], c: 2 },
      { q: "Which peace conference redrew Europe's map after the Napoleonic Wars?", a: ["Congress of Vienna", "Yalta Conference", "Treaty of Utrecht", "Potsdam Conference"], c: 0 },
      { q: "Who was the Mongol leader who founded the largest contiguous empire?", a: ["Kublai Khan", "Genghis Khan", "Attila", "Tamerlane"], c: 1 },
      { q: "The Rosetta Stone was key to deciphering which writing system?", a: ["Cuneiform", "Egyptian hieroglyphs", "Linear B", "Runes"], c: 1 },
      { q: "Which US president issued the Emancipation Proclamation?", a: ["Washington", "Jefferson", "Lincoln", "Grant"], c: 2 },
      { q: "The Meiji Restoration modernized which country in the 19th century?", a: ["China", "Japan", "Korea", "Thailand"], c: 1 },
      { q: "Which ancient civilization created the first known written law code (Hammurabi)?", a: ["Egypt", "Babylon", "Greece", "Persia"], c: 1 },
      { q: "In what year did the Soviet Union officially dissolve?", a: ["1985", "1989", "1991", "1993"], c: 2 },
    ],
  },
  "Words & Language": {
    1: [
      { q: "What is the opposite of 'happy'?", a: ["Sad", "Angry", "Tired", "Fast"], c: 0 },
      { q: "Which word is a color?", a: ["Table", "Blue", "Jump", "Loud"], c: 1 },
      { q: "How many letters are in the English alphabet?", a: ["24", "25", "26", "27"], c: 2 },
      { q: "What is the plural of 'cat'?", a: ["Cat", "Cats", "Cates", "Cati"], c: 1 },
      { q: "Which word means a young dog?", a: ["Kitten", "Puppy", "Calf", "Foal"], c: 1 },
      { q: "What punctuation ends a question?", a: ["Period", "Comma", "Question mark", "Colon"], c: 2 },
      { q: "Which of these is a vowel?", a: ["B", "E", "T", "R"], c: 1 },
      { q: "What is the opposite of 'up'?", a: ["Down", "Left", "Over", "Around"], c: 0 },
      { q: "Which word rhymes with 'cat'?", a: ["Dog", "Hat", "Cup", "Pen"], c: 1 },
      { q: "What do you call words that mean the same thing?", a: ["Antonyms", "Synonyms", "Homonyms", "Acronyms"], c: 1 },
    ],
    2: [
      { q: "What do you call words with opposite meanings?", a: ["Synonyms", "Antonyms", "Homonyms", "Pronouns"], c: 1 },
      { q: "Which word is a noun?", a: ["Run", "Quickly", "Dog", "Blue"], c: 2 },
      { q: "What is the past tense of 'go'?", a: ["Goed", "Gone", "Went", "Going"], c: 2 },
      { q: "Which word is spelled correctly?", a: ["Recieve", "Receive", "Receeve", "Receve"], c: 1 },
      { q: "What does 'ASAP' stand for?", a: ["As slow as possible", "As soon as possible", "Always ship and print", "A special agent process"], c: 1 },
      { q: "Which of these is a preposition?", a: ["Under", "Happy", "Quickly", "Table"], c: 0 },
      { q: "What is a group of words expressing a complete thought called?", a: ["Phrase", "Clause", "Sentence", "Syllable"], c: 2 },
      { q: "Which word means 'very big'?", a: ["Tiny", "Enormous", "Narrow", "Brief"], c: 1 },
      { q: "What is the past tense of 'run'?", a: ["Runned", "Ran", "Run", "Running"], c: 1 },
      { q: "What punctuation joins two related independent clauses?", a: ["Comma", "Semicolon", "Hyphen", "Apostrophe"], c: 1 },
    ],
    3: [
      { q: "What does the idiom 'break the ice' mean?", a: ["To start a conversation", "To feel cold", "To fail", "To be angry"], c: 0 },
      { q: "Which word is an adverb?", a: ["Beautiful", "Beauty", "Beautifully", "Beautify"], c: 2 },
      { q: "What is the correct contraction for 'they are'?", a: ["Their", "There", "They're", "Theyre"], c: 2 },
      { q: "A word that imitates a sound (like 'buzz') is an example of?", a: ["Metaphor", "Onomatopoeia", "Alliteration", "Simile"], c: 1 },
      { q: "Which is the correct spelling?", a: ["Definately", "Definitely", "Definitly", "Definetly"], c: 1 },
      { q: "What does 'et cetera' (etc.) mean?", a: ["The end", "And so on", "For example", "In summary"], c: 1 },
      { q: "A comparison using 'like' or 'as' is a?", a: ["Metaphor", "Simile", "Hyperbole", "Pun"], c: 1 },
      { q: "Which word is a synonym for 'happy'?", a: ["Miserable", "Joyful", "Anxious", "Weary"], c: 1 },
      { q: "What part of speech is the word 'quickly'?", a: ["Noun", "Verb", "Adjective", "Adverb"], c: 3 },
      { q: "What does the prefix 're-' generally mean?", a: ["Not", "Again", "Before", "Against"], c: 1 },
    ],
    4: [
      { q: "What does the idiom 'bite the bullet' mean?", a: ["To eat quickly", "To endure a painful situation", "To make a mistake", "To stay quiet"], c: 1 },
      { q: "What is a word that reads the same forwards and backwards called?", a: ["Anagram", "Palindrome", "Homophone", "Acronym"], c: 1 },
      { q: "Which sentence is grammatically correct?", a: ["Me and him went", "Him and me went", "He and I went", "I and he went"], c: 2 },
      { q: "The exaggeration 'I've told you a million times' is an example of?", a: ["Irony", "Hyperbole", "Metaphor", "Alliteration"], c: 1 },
      { q: "What does 'ubiquitous' mean?", a: ["Rare", "Present everywhere", "Ancient", "Hidden"], c: 1 },
      { q: "Which is the correct plural of 'cactus'?", a: ["Cactuses/Cacti", "Cactus", "Cactie", "Cactusi"], c: 0 },
      { q: "What is the term for a mild word substituted for a harsh one (e.g., 'passed away')?", a: ["Euphemism", "Idiom", "Cliché", "Oxymoron"], c: 0 },
      { q: "'Deafening silence' is an example of which figure of speech?", a: ["Simile", "Oxymoron", "Metaphor", "Pun"], c: 1 },
      { q: "What does the Latin phrase 'vice versa' mean?", a: ["In good faith", "The other way around", "At first glance", "For this purpose"], c: 1 },
      { q: "Which word means 'to formally give up a throne'?", a: ["Abdicate", "Advocate", "Adjudicate", "Allocate"], c: 0 },
    ],
    5: [
      { q: "What does the word 'sesquipedalian' describe?", a: ["Something tiny", "Long words / given to using long words", "A type of dance", "A number"], c: 1 },
      { q: "What is the term for a phrase like 'jumbo shrimp' (contradictory terms)?", a: ["Euphemism", "Oxymoron", "Tautology", "Malapropism"], c: 1 },
      { q: "What does 'ephemeral' mean?", a: ["Lasting a very short time", "Extremely large", "Deeply hidden", "Frequently repeated"], c: 0 },
      { q: "A 'malapropism' is best described as?", a: ["A wise saying", "Mistaken use of a similar-sounding word", "A rhyming couplet", "An invented word"], c: 1 },
      { q: "What is the longest common word typed with only the left hand on a QWERTY keyboard?", a: ["Stewardesses", "Typewriter", "Alphabet", "Keyboard"], c: 0 },
      { q: "What does 'quintessential' mean?", a: ["The fifth attempt", "The most perfect example", "Barely adequate", "Completely new"], c: 1 },
      { q: "The word 'defenestration' refers to the act of?", a: ["Removing shoes", "Throwing someone out a window", "Cutting hair", "Locking a door"], c: 1 },
      { q: "What is a 'portmanteau' word?", a: ["A borrowed foreign word", "A blend of two words (e.g., brunch)", "A word said in error", "A very old word"], c: 1 },
      { q: "What does 'pulchritudinous' mean?", a: ["Ugly", "Beautiful", "Talkative", "Wealthy"], c: 1 },
      { q: "Which term describes a word that sounds the same but differs in meaning and spelling?", a: ["Homograph", "Homophone", "Synonym", "Antonym"], c: 1 },
    ],
  },
  "Movies & TV": {
    1: [
      { q: "In 'The Lion King', what kind of animal is Simba?", a: ["Tiger", "Lion", "Leopard", "Cheetah"], c: 1 },
      { q: "Which movie features a snowman named Olaf?", a: ["Moana", "Frozen", "Tangled", "Encanto"], c: 1 },
      { q: "What is the name of the yellow, pill-shaped characters in 'Despicable Me'?", a: ["Minions", "Smurfs", "Oompas", "Trolls"], c: 0 },
      { q: "In 'Finding Nemo', Nemo is what kind of fish?", a: ["Goldfish", "Clownfish", "Shark", "Tuna"], c: 1 },
      { q: "Which superhero wears a red and blue suit and shoots webs?", a: ["Batman", "Iron Man", "Spider-Man", "Flash"], c: 2 },
      { q: "What is the name of the toy cowboy in 'Toy Story'?", a: ["Buzz", "Woody", "Rex", "Hamm"], c: 1 },
      { q: "Which movie has a wizard boy named Harry?", a: ["Narnia", "Harry Potter", "Percy Jackson", "Eragon"], c: 1 },
      { q: "What green character says 'That's all folks' — no, who says 'I'm lovin' it'? (Pick the cartoon rabbit)", a: ["Bugs Bunny", "Mickey Mouse", "Donald Duck", "Tom"], c: 0 },
      { q: "In 'Cars', what is the main character Lightning McQueen?", a: ["A plane", "A race car", "A truck", "A boat"], c: 1 },
      { q: "Which show features a talking sponge who lives in a pineapple?", a: ["Rugrats", "SpongeBob SquarePants", "Doug", "Hey Arnold"], c: 1 },
    ],
    2: [
      { q: "Who directed the movie 'Jaws'?", a: ["George Lucas", "Steven Spielberg", "James Cameron", "Ridley Scott"], c: 1 },
      { q: "In 'Star Wars', what is the name of Luke Skywalker's father?", a: ["Han Solo", "Darth Vader", "Obi-Wan", "Yoda"], c: 1 },
      { q: "Which TV show features the fictional Central Perk coffee house?", a: ["Seinfeld", "Friends", "Cheers", "How I Met Your Mother"], c: 1 },
      { q: "What is the highest-grossing film franchise about a boy wizard?", a: ["Lord of the Rings", "Harry Potter", "Narnia", "Percy Jackson"], c: 1 },
      { q: "In 'The Wizard of Oz', what does Dorothy click together to go home?", a: ["Her hands", "Her ruby slippers", "A wand", "A locket"], c: 1 },
      { q: "Which animated studio made 'Toy Story'?", a: ["DreamWorks", "Pixar", "Illumination", "Studio Ghibli"], c: 1 },
      { q: "What is the name of the kingdom in Disney's 'Frozen'?", a: ["Arendelle", "Corona", "Agrabah", "Motunui"], c: 0 },
      { q: "Who plays the character of Jack in 'Titanic'?", a: ["Brad Pitt", "Leonardo DiCaprio", "Tom Cruise", "Matt Damon"], c: 1 },
      { q: "Which sci-fi series is set on the starship Enterprise?", a: ["Star Wars", "Star Trek", "Battlestar Galactica", "The Expanse"], c: 1 },
      { q: "What color is the Hulk?", a: ["Blue", "Red", "Green", "Purple"], c: 2 },
    ],
    3: [
      { q: "Which film won the first Academy Award for Best Animated Feature?", a: ["Toy Story", "Shrek", "Finding Nemo", "Monsters, Inc."], c: 1 },
      { q: "In 'The Godfather', what is the family's surname?", a: ["Soprano", "Corleone", "Montana", "Gambino"], c: 1 },
      { q: "Who directed 'Pulp Fiction'?", a: ["Martin Scorsese", "Quentin Tarantino", "Coen Brothers", "David Fincher"], c: 1 },
      { q: "Which TV series is set in the fictional town of Hawkins with a place called the Upside Down?", a: ["Stranger Things", "Twin Peaks", "Riverdale", "The X-Files"], c: 0 },
      { q: "What is the name of the ring in 'The Lord of the Rings'?", a: ["The One Ring", "The Ring of Power only", "The Elven Ring", "The Dark Ring"], c: 0 },
      { q: "Which actor played Jack Sparrow in 'Pirates of the Caribbean'?", a: ["Orlando Bloom", "Johnny Depp", "Russell Crowe", "Colin Farrell"], c: 1 },
      { q: "Which movie features the quote 'Here's looking at you, kid'?", a: ["Gone with the Wind", "Casablanca", "Citizen Kane", "The Maltese Falcon"], c: 1 },
      { q: "What TV show features a chemistry teacher named Walter White?", a: ["Breaking Bad", "The Wire", "Dexter", "Ozark"], c: 0 },
      { q: "Which franchise features characters named Neo and Trinity?", a: ["Blade Runner", "The Matrix", "Tron", "Inception"], c: 1 },
      { q: "Who composed the iconic score for 'Star Wars'?", a: ["Hans Zimmer", "John Williams", "Danny Elfman", "Ennio Morricone"], c: 1 },
    ],
    4: [
      { q: "Which film won the Academy Award for Best Picture and is set on the sinking Titanic?", a: ["Titanic", "The English Patient", "Braveheart", "Forrest Gump"], c: 0 },
      { q: "Who directed the 'Alien' (1979) film?", a: ["James Cameron", "Ridley Scott", "John Carpenter", "Steven Spielberg"], c: 1 },
      { q: "In 'The Silence of the Lambs', what is the surname of Dr. Hannibal?", a: ["Lecter", "Crane", "Bates", "Gein"], c: 0 },
      { q: "Which director is known for 'Vertigo', 'Psycho', and 'The Birds'?", a: ["Orson Welles", "Alfred Hitchcock", "Stanley Kubrick", "Billy Wilder"], c: 1 },
      { q: "What is the name of the fictional African nation in 'Black Panther'?", a: ["Zamunda", "Wakanda", "Genosha", "Sokovia"], c: 1 },
      { q: "Which 1994 film features the line 'Life is like a box of chocolates'?", a: ["Forrest Gump", "The Shawshank Redemption", "Pulp Fiction", "Speed"], c: 0 },
      { q: "Who played the Joker in 'The Dark Knight' (2008)?", a: ["Jack Nicholson", "Heath Ledger", "Joaquin Phoenix", "Jared Leto"], c: 1 },
      { q: "Which TV drama features the Iron Throne?", a: ["The Witcher", "Game of Thrones", "Vikings", "The Last Kingdom"], c: 1 },
      { q: "Which Studio Ghibli film features a girl named Chihiro?", a: ["My Neighbor Totoro", "Spirited Away", "Princess Mononoke", "Ponyo"], c: 1 },
      { q: "Who directed 'Inception' and 'Interstellar'?", a: ["Denis Villeneuve", "Christopher Nolan", "Ridley Scott", "James Cameron"], c: 1 },
    ],
    5: [
      { q: "Which film was the first to win all top five Academy Awards (Picture, Director, Actor, Actress, Screenplay)?", a: ["Gone with the Wind", "It Happened One Night", "Casablanca", "Ben-Hur"], c: 1 },
      { q: "Who directed the 1927 partly-silent film milestone 'The Jazz Singer'? (studio: Warner Bros.) — which studio released it?", a: ["MGM", "Warner Bros.", "Paramount", "RKO"], c: 1 },
      { q: "In 'Citizen Kane', what is the meaning of 'Rosebud'?", a: ["A hotel", "His childhood sled", "A newspaper", "His wife"], c: 1 },
      { q: "Which actress has won the most competitive Academy Awards for acting?", a: ["Meryl Streep", "Katharine Hepburn", "Bette Davis", "Ingrid Bergman"], c: 1 },
      { q: "Which director made 'Seven Samurai' and 'Rashomon'?", a: ["Akira Kurosawa", "Yasujiro Ozu", "Hayao Miyazaki", "Kenji Mizoguchi"], c: 0 },
      { q: "What was the first feature film to be released with synchronized recorded sound dialogue (widely cited)?", a: ["Metropolis", "The Jazz Singer", "Nosferatu", "The General"], c: 1 },
      { q: "Which 1968 Kubrick film features the AI computer HAL 9000?", a: ["A Clockwork Orange", "2001: A Space Odyssey", "The Shining", "Dr. Strangelove"], c: 1 },
      { q: "Who is the only person to win an Oscar for playing a character across two films (same role) — for Vito Corleone in the sequel?", a: ["Marlon Brando", "Robert De Niro", "Al Pacino", "Robert Duvall"], c: 1 },
      { q: "Which TV series holds a record for most Emmy wins for a scripted show (drama, HBO fantasy)?", a: ["The Sopranos", "Game of Thrones", "Breaking Bad", "Mad Men"], c: 1 },
      { q: "Which silent-era comedian directed and starred in 'The Gold Rush' (1925)?", a: ["Buster Keaton", "Charlie Chaplin", "Harold Lloyd", "Fatty Arbuckle"], c: 1 },
    ],
  },
};
